# Generated by Django 2.1.3 on 2019-02-19 15:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0004_auto_20190219_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='highscore',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default="{'1':{}, '2':{}, '3':{}, '4':{}, '5':{}}", null=True),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='score',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default="{'1':0, '2':0, '3':0, '4':0, '5':0}", null=True),
        ),
    ]
