# Generated by Django 2.1.3 on 2019-02-19 15:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0005_auto_20190219_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='highscore',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='score',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
