# Generated by Django 2.1.3 on 2019-02-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameshop', '0007_auto_20190219_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='highscore',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
